/**
 * Stable, machine-readable error codes. Clients branch on these strings, so they are part
 * of the public API contract: rename one and you break every consumer.
 *
 * The first sixteen are the taxonomy from the technical design; the remainder are
 * documented extensions needed once idempotency and abuse controls became concrete.
 */
export const ErrorCode = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  SLOT_ALREADY_HELD: 'SLOT_ALREADY_HELD',
  HOLD_NOT_FOUND: 'HOLD_NOT_FOUND',
  HOLD_EXPIRED: 'HOLD_EXPIRED',
  HOLD_NOT_OWNED: 'HOLD_NOT_OWNED',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',
  RECURRING_CONFLICT: 'RECURRING_CONFLICT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  MAX_ACTIVE_HOLDS_EXCEEDED: 'MAX_ACTIVE_HOLDS_EXCEEDED',
  SCHEDULE_CONFLICT: 'SCHEDULE_CONFLICT',
  SERIES_ALREADY_CANCELLED: 'SERIES_ALREADY_CANCELLED',
  APPOINTMENT_ALREADY_CANCELLED: 'APPOINTMENT_ALREADY_CANCELLED',
  OUTSIDE_STATUS_WINDOW: 'OUTSIDE_STATUS_WINDOW',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCodeValue, number>> = Object.freeze({
  [ErrorCode.AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.SLOT_NOT_AVAILABLE]: 409,
  [ErrorCode.SLOT_ALREADY_HELD]: 409,
  [ErrorCode.HOLD_NOT_FOUND]: 404,
  [ErrorCode.HOLD_EXPIRED]: 409,
  [ErrorCode.HOLD_NOT_OWNED]: 403,
  [ErrorCode.APPOINTMENT_CONFLICT]: 409,
  [ErrorCode.RECURRING_CONFLICT]: 409,
  [ErrorCode.INVALID_STATUS_TRANSITION]: 409,
  [ErrorCode.IDEMPOTENCY_KEY_REUSED]: 422,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,

  [ErrorCode.IDEMPOTENCY_IN_PROGRESS]: 409,
  [ErrorCode.IDEMPOTENCY_KEY_REQUIRED]: 400,
  [ErrorCode.MAX_ACTIVE_HOLDS_EXCEEDED]: 429,
  [ErrorCode.SCHEDULE_CONFLICT]: 409,
  [ErrorCode.SERIES_ALREADY_CANCELLED]: 409,
  [ErrorCode.APPOINTMENT_ALREADY_CANCELLED]: 409,
  [ErrorCode.OUTSIDE_STATUS_WINDOW]: 403,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.PAYLOAD_TOO_LARGE]: 413,
});
