-- ===========================================================================
-- 0001_foundation
--
-- Extensions, shared helpers, identity and the refresh-token store.
--
-- Conventions used throughout these migrations:
--   * Every timestamp is TIMESTAMPTZ. There is no ambiguity about what "10:00" means.
--   * Enumerations are TEXT + CHECK rather than native PG enums. Adding a value to a
--     native enum cannot run inside a transaction with other DDL on older versions and
--     removing one is effectively impossible; a CHECK constraint is trivially revisable.
--   * Identifiers are UUIDs generated by the database (gen_random_uuid, built in since
--     PG13) so that a client can never dictate a primary key.
-- ===========================================================================

-- Teaches GiST how to index scalar equality (therapist_id) next to a range, which is what
-- makes the "no overlapping appointments *per therapist*" exclusion constraint possible.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------------
-- Shared trigger: keep updated_at honest.
-- Doing this in the database rather than the application guarantees it is correct even
-- for an ad-hoc UPDATE run during an incident.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- users
-- Both roles live in one table: they authenticate identically and the role drives
-- authorization. Patients have no separate profile table because the domain does not yet
-- need one, and inventing empty tables is a cost with no benefit.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT        NOT NULL,
  password_hash TEXT        NOT NULL,
  role          TEXT        NOT NULL,
  full_name     TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'ACTIVE',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT users_role_check   CHECK (role IN ('PATIENT', 'THERAPIST')),
  CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'DISABLED')),
  CONSTRAINT users_email_format_check CHECK (email = lower(email) AND position('@' IN email) > 1)
);

-- Case-insensitive uniqueness without the citext extension. Emails are stored already
-- lowercased (enforced above) so a plain unique index is enough and stays index-only.
CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- therapists
-- A therapist is a professional profile attached to a user account. Appointments point at
-- the therapist profile, not the login, so that account changes never rewrite booking history.
-- ---------------------------------------------------------------------------
CREATE TABLE therapists (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  display_name   TEXT        NOT NULL,
  specialization TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT therapists_user_id_key UNIQUE (user_id)
);

CREATE TRIGGER therapists_set_updated_at
  BEFORE UPDATE ON therapists
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- refresh_tokens
--
-- Refresh tokens are rotated on every use. Each login starts a "family"; a rotation
-- issues a new member of the same family and revokes its predecessor.
--
-- Why families: if a stolen token is replayed after the legitimate client already rotated
-- it, we see a *revoked* token being presented. That is unambiguous evidence of theft, so
-- we revoke the entire family and force re-authentication. Without this, a stolen refresh
-- token grants indefinite access.
--
-- Only a SHA-256 hash is stored. A database dump must not yield usable credentials.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  family_id      UUID        NOT NULL,
  token_hash     TEXT        NOT NULL,
  issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at     TIMESTAMPTZ NOT NULL,
  used_at        TIMESTAMPTZ,
  revoked_at     TIMESTAMPTZ,
  revoked_reason TEXT,
  replaced_by    UUID REFERENCES refresh_tokens (id) ON DELETE SET NULL,

  CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash),
  CONSTRAINT refresh_tokens_revoked_reason_check
    CHECK (revoked_reason IS NULL OR revoked_reason IN ('ROTATED', 'LOGOUT', 'REUSE_DETECTED', 'EXPIRED', 'ADMIN')),
  CONSTRAINT refresh_tokens_expiry_check CHECK (expires_at > issued_at)
);

CREATE INDEX refresh_tokens_user_id_idx   ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_family_id_idx ON refresh_tokens (family_id);
-- Supports the cleanup job without scanning live rows.
CREATE INDEX refresh_tokens_expires_at_idx ON refresh_tokens (expires_at) WHERE revoked_at IS NULL;
